######### This document describes how I used deepTools to plot enrichment heatmaps (comparing bigwigs) of ChIP-seq datasets.

# In this particular example, I create a plot comparing enrichment of TBX5, HOXA13, and H3K27ac signal in the mouse genital tubercle. Peaks are binned into two groups: TBX5-HOXA13-shared peaks (blue line) and TB5-specific peaks (red line).

# Here is the link to the figure: https://user-images.githubusercontent.com/61433004/231881114-baa6c5f1-e411-4918-9377-bee69cd0ca36.jpg


# deepTools Documentation: https://deeptools.readthedocs.io/en/develop/

### First make sure you install Anaconda in Linux Mint: https://docs.anaconda.com/anaconda/install/linux/

### Then, install deepTools:
# First, create a conda environment:

conda create --name myenvdeeptools

# Then, activate the environment:

conda activate myenvdeeptools

# Now, continue with installation

conda install -c conda-forge -c bioconda deeptools

### Anytime you want to run deepTools, make sure to activate the environment first using the activate command above.



### Before running deepTools, you first need to create a matrix file generated by the tool computeMatrix.
# To do this, you need to select the bigwigs you want to visualize. Then you need to create .bed files of peak coordinates you want to visualize. In this example, I centered TBX5 peak summits in a 1 kb window. I create two seperate .bed files (TBX5-HOXA13-shared peaks and TBX5-specific peaks) so I can bin the visualization into two groups.

# computeMatrix command:
computeMatrix reference-point \
--referencePoint center \
-R mm10_TBX5_GT_vs_HOXA13_CnR_d100_Amândio_Duboule_intersected_v1_1000bp.bed \
mm10_TBX5_GT_vs_HOXA13_CnR_d100_Amândio_Duboule--TBX5-specific_v1_1000bp.bed \
-S TBX5_GT_E12.5_090221_IDR_rep.pooled_x_ctl.pooled.fc.signal.bigwig \
mm_GT_E13.5_HOXA13.bw \
H3K27ac_GT_SRR1703000.nodup_SRR1703001.nodup.tagAlign_x_SRR1703002.nodup.tagAlign.fc.signal.bw \
--upstream 500 \
--downstream 500 \
--binSize 1 \
-o matrix_TBX5-HOXA13-H3K27ac--GT--Tbx5-Hoxa13-peaks_v1.gz


# See here for a description of all the arguments above: https://deeptools.readthedocs.io/en/develop/content/tools/computeMatrix.html

### Once you have the .gz matrix file, you can use this to plot the heatmap:
plotHeatmap -m matrix_TBX5-HOXA13-H3K27ac--GT--Tbx5-Hoxa13-peaks_v1.gz  \
--colorMap Greys \
--legendLocation none \
--yMin 0 0 1.5 --yMax 11 20 4.5 \
--zMin 0 0 0 --zMax 12 30 12 \
-x . \
--regionsLabel "6,691 TBX5 + HOXA13" "14,037 TBX5-specific" \
--samplesLabel TBX5 HOXA13 H3K27ac \
-out TBX5-HOXA13-H3K27ac--GT--Tbx5-Hoxa13-peaks_Heatmap_v5b.pdf

# See here for a description of all the arguments above: https://deeptools.readthedocs.io/en/develop/content/tools/plotHeatmap.html


# After generation of plots, vector graphics (in the PDF file) were edited in Adobe Illustrator. Final figures were assembled for publication in Adobe InDesign.



